### ISSUE TITLE
Save operation requires redefining target file every time

### ISSUE THREAD

**Issue by holthopkins** [countincognito/Zametek.ProjectPlan#13]
When working on an open file I find I have to explicitly specify the file I'm saving to every time I chose Save.  The application does not default to the file last saved for the original file opened.  This can lead to overwriting the wrong file.

**Comment by countincognito** [comment]
This should be implemented in v0.4.0:
https://github.com/countincognito/Zametek.ProjectPlan/releases/tag/v0.4.0
