### ISSUE TITLE
Add mouse-over labels for acronyms

### ISSUE THREAD

**Issue by Kralizek** [countincognito/Zametek.ProjectPlan#15]
The activity table is dense of information and acronyms are ok not to disperse the attention of the user.

On the other hand, a label to be displayed on mouseover that writes in full would be a really nice QoL improvement :)

e.g. mousovering the header of the EST column should display "Earliest Start Time" and so on...

![image](https://user-images.githubusercontent.com/2458439/45928730-c6e13a80-bf48-11e8-9dbd-47e58c880021.png)

**Comment by countincognito** [comment]
Done in release [v0.4.2](https://github.com/countincognito/Zametek.ProjectPlan/releases/tag/v0.4.2)
