### ISSUE TITLE
v0.4.1.zip - Virus Threat

### ISSUE THREAD

**Issue by sharpoverride** [countincognito/Zametek.ProjectPlan#16]
Hi,

I was attempting to download the latest release. But Windows Defender reports it as containing a virus.

![image](https://user-images.githubusercontent.com/208198/68646731-ab5a3a00-0524-11ea-8dfa-199b7f0b3216.png)

Please verify this is not the case.

**Comment by countincognito** [comment]
@sharpoverride This certainly isn't the case with the zip file when I download it. Did you download it directly from github?

If you have any doubts then you could simply build the latest version from source.

**Comment by sharpoverride** [comment]
@countincognito Yes, I downloaded it directly from the Releases on Github. Probably the best option is to just build it myself :)

**Comment by countincognito** [comment]
@sharpoverride The problem is most likely because the download contains an unverified installer exe (the installer is purely for convenience - nothing sophisticated at all). Building from source is best if in doubt. Thanks for trying it out!
