### ISSUE TITLE
Enable paste of activities from excel 

### ISSUE THREAD

**Issue by Tovli** [countincognito/Zametek.ProjectPlan#20]
As a project designer I want to be able to copy activities I've prepared in Excel into the activities view of project plan

This will allow non MS project users to utilize excel powers to set the activities in an easy to share way

If you can guide where I can start, I will find the time to set a PR as I believe it shouldn't be too hard

**Comment by countincognito** [comment]
@Tovli Do you have a sample Excel sheet you can share?

**Comment by Tovli** [comment]
[ProjectDesignSample.xlsx](https://github.com/countincognito/Zametek.ProjectPlan/files/4639670/ProjectDesignSample.xlsx)

This is a sample but I'm really open to any way you find easy to develop and can help me get data from excel or csv file to project plan

Thanks

**Comment by countincognito** [comment]
Not pasting, but import from Excel is not possible in [v0.7.0](https://github.com/countincognito/Zametek.ProjectPlan/releases/tag/v0.7.0).
