### ISSUE TITLE
Project Efficiency

### ISSUE THREAD

**Issue by gcfreddy** [countincognito/Zametek.ProjectPlan#21]
Project Efficiency defined as the ratio between man-days/month of allocated to all activities and the total cost of the project is a feature that could be added to the program.

The computation of Project Efficiency requires some manual work. For cases where all activities are assigned to only one resource, the Project Efficiency computation is kind of trivial given the export from Earned Value Chart tab provides the sum of the duration of all activities. However, when there are activities where more than one resource is assigned to them the computation requires several manual steps, for this case you need to build the list of activities with their duration and assigned resources.

So, it would be nice to have the Project Efficiency computed and displayed on the Activities Tab, even a way to export the activities with their duration and amount of assigned resources would be nice for a crosscheck and exploration of other options.

**Comment by countincognito** [comment]
Added in [v0.7.0](https://github.com/countincognito/Zametek.ProjectPlan/releases/tag/v0.7.0).
