### ISSUE TITLE
Allow half day activity duration or less

### ISSUE THREAD

**Issue by marianagun** [countincognito/Zametek.ProjectPlan#22]
It is not possible to add a half day activity duration or less. I have some tasks that are 4 hrs, 2 hrs or 1 hr, and it is not possible to include this detail. I have a project where I have for example 3 tasks that sum 7 hs (it is 1 day), but I get a planning of 3 days instead. 
Thanks for your help!
Regards, 
Marian

**Comment by jeffdoolittle** [comment]
At the level of Project Design, activities should always be measured in 5 day increments at the minimum. Attempts to estimate at the precision of hours will remove all benefits from the law of large numbers when planning and estimating.

**Comment by countincognito** [comment]
As @jeffdoolittle mentioned, this is by design. Durations that are less than a day are really too granular to be useful in a tool like this.
