### ISSUE TITLE
Include Printing options

### ISSUE THREAD

**Issue by marianagun** [countincognito/Zametek.ProjectPlan#23]
As a user, I would like to be able to print to PDF or JPG every chart and graph available.

**Comment by countincognito** [comment]
@marianagun have you tried the "Chart To Clipboard" buttons? These copy images of the charts to the clipboard for pasting. You can use the height and width settings to change the dimensions of the copied image.

**Comment by marianagun** [comment]
Hi @countincognito ! Yes, but it is not possible to export Activities, Gantt Chart and Arrow Graph. Thanks for your reply!

**Comment by countincognito** [comment]
@marianagun can you please describe what you would like to see as outputs for the activities and the gantt chart.

The arrow graph can be exported to graphML format. See here:
https://github.com/countincognito/Zametek.ProjectPlan/wiki/Outputs#export-arrow-graph-graphml

Many thanks

**Comment by marianagun** [comment]
Sure @countincognito ! For the Gantt Chart, the possibility to export to PDF or a format that allows me see the full picture:
![image](https://user-images.githubusercontent.com/47987639/93262320-69200b80-f77a-11ea-84e4-6c527692e7ed.png)
I can't export or print the full picture in the timeline. 

For the Arrow Graph, I suggest adding the "Chat to Clipboard" option, and a more complete option with the Tasks and Duration included:
![image](https://user-images.githubusercontent.com/47987639/93262502-b8fed280-f77a-11ea-8119-7ca2b4aef66e.png)
I have to use the Gantt as a reference anyways. Maybe it will be useful to have a footer or something including Tasks and Durations, Resources that appear in the Activity part. It gives more detail in the same page of the Graph. This way, I can share it with the tasks and durations included to give a clear picture. Thanks!

**Comment by countincognito** [comment]
@marianagun thank you for these suggestions. I will take them on board for the next release.

Regarding the gantt chart, that's a tough one: the chart itself is built from scratch using an old library I repurposed (all the other gantt libraries were not open source), so exporting it as an image would be a lot of work. Perhaps a better solution would be some sort of text-based export that users could render themselves if necessary. I will have to think about that one.

Regarding arrow graph export, I would strongly advise that you try the methods recommended in the documentation (i.e. GraphML with yEd). The outputs from yEd are excellent, and they offer a much richer editing experience than ProjectPlan does.

On the question of task summaries in the footer of the arrow chart, have you tried stacking the tabs to achieve the same purpose? ProjectPlan uses AvalonDock, so you can stack the tabs in much the same way as you would in Visual Studio (see below). Obviously, the bigger the screen, the easier it is to see.

![stacked_tabs](https://user-images.githubusercontent.com/1745990/93388338-79131a80-f862-11ea-9af0-84135248bff5.jpg)

**Comment by marianagun** [comment]
Regarding the Gantt Chart, no need to do it, just was a suggestion! I can work with something else. 

Regarding the Arrow Graph export, I will try those tools, thank you very much!

Regarding stacking, that solves my issue too!! I didn't know I could stack them. 

Thanks so much @countincognito !!!

**Comment by countincognito** [comment]
Added in [v0.7.1](https://github.com/countincognito/Zametek.ProjectPlan/releases/tag/v0.7.1).
