### ISSUE TITLE
Allow to change Start Dates forward for some tasks to other than the Project Start

### ISSUE THREAD

**Issue by marianagun** [countincognito/Zametek.ProjectPlan#24]
As a user, I need to change some of the Start Dates forward for some tasks to other than the Project Start. 
I have a situation when I need some resources to join 15 and 21 days later, and not at the very beginning of the project. Other resources will join on 2021. I am not able to add them as the Start Date is forced to be the beginning of the project. In MS Project this is a "Start no earlier than" constraint. Thanks!!

**Comment by countincognito** [comment]
@marianagun for this you can use the Minimum EST (Earliest Start Time). It achieves the same thing:

https://github.com/countincognito/Zametek.ProjectPlan/wiki/Activities#minimum-fs-minimum-est-and-maximum-lft

**Comment by marianagun** [comment]
It worked perfect, thanks! I don't know why I omitted it.
