### ISSUE TITLE
Export Bundle

### ISSUE THREAD

**Issue by jeffdoolittle** [countincognito/Zametek.ProjectPlan#26]
It would be nice to run a single command to generate export files and images (when available) for Gantt Chart (#25), Arrow Graph, Resource Chart and Earned Value Chart.

This would be very useful when preparing presentations of the Software Design Plan.

It would be even better if the app included the ability to add markdown notes and then generate a markdown file that contains all the appropriate visual artifacts inline with your markdown notes.

**Comment by jeffdoolittle** [comment]
Including a summary of all the calculations in the header of the Activities panel.

**Comment by countincognito** [comment]
Projects can now be exported to Excel in [v0.7.0](https://github.com/countincognito/Zametek.ProjectPlan/releases/tag/v0.7.0), and each chart can be directly exported by right-clicking the screen.

**Comment by countincognito** [comment]
@jeffdoolittle I would like to build on the new export capabilities recently introduced. Have you got a sample of the sort of bundle you had in mind (a tangible document I can look at)? Thanks.

**Comment by jeffdoolittle** [comment]
I don't have anything specific. I was thinking about starting with the ability to export PNG images of all charts to a folder as a good beginning.

**Comment by countincognito** [comment]
This is now available from v0.8.1
