### ISSUE TITLE
Reintroduce Gantt Chart

### ISSUE THREAD

**Issue by jeffdoolittle** [countincognito/Zametek.ProjectPlan#39]

**Comment by MattMinke** [comment]
The Gantt chart is beneficial when sharing timelines in a visual way with non-technical members. I would agree adding the Gantt Chart back would be a great feature.

**Comment by jeffdoolittle** [comment]
It looks like one option would be to port the original nGantt project to AvaloniaUI.

https://github.com/danwallentin/nGantt

**Comment by countincognito** [comment]
Added in [v0.7.1](https://github.com/countincognito/Zametek.ProjectPlan/releases/tag/v0.7.1).
