### ISSUE TITLE
Graph improvements

### ISSUE THREAD

**Issue by emilw** [countincognito/Zametek.ProjectPlan#49]
Really nice tool!

Improvements that would be nice are:
- Be able to see the resource without hoovering over them when using Anotate group. Its hard to share the plan now without needing to explain what the colors mean
![image](https://github.com/user-attachments/assets/9fb655f5-2af8-4d5e-88de-3bbad15c457a)
- See an end date of the project, in the graphs there is no end date visible.
- Looking at the metrics summarization you can see total duration in month, but no end date

**Comment by countincognito** [comment]
Great suggestions! I will try to get these in the next release. I am not sure if getting the end date in the Gantt Chart will be possible, but I will see what I can do. Or did you mean including it in the Arrow Graph?

**Comment by emilw** [comment]
Hi,
I meant in the Gant chart. That is for me the main view where I can show how teams are allocated etc.
If that is not possible maybe it can be annotated in the top right corner: “Current end date:….” Or similar.

Thanks

**Comment by countincognito** [comment]
@emilw This is now included in the develop branch and should be available in the next release.

**Comment by LarsKemmann** [comment]
This is working well (for me at least) in the v0.9.0-beta.1 release. @emilw Does it work for you? I think this can be closed. 😊

**Comment by emilw** [comment]
Yes, brilliant 👍
Forgot responding, thanks for your effort!

**Comment by countincognito** [comment]
Now available in [v0.9.0](https://github.com/countincognito/Zametek.ProjectPlan/releases/tag/v0.9.0)
