### ISSUE TITLE
Theme switcher/dark mode default

### ISSUE THREAD

**Issue by LarsKemmann** [countincognito/Zametek.ProjectPlan#54]
Now that you have two new themes (if I read [the release notes](https://github.com/countincognito/Zametek.ProjectPlan/releases/tag/v0.9.0-alpha) correctly), can you provide a way for us to switch themes? Or even default to the dark mode based on the operating system defaults?

**Comment by countincognito** [comment]
I think this can be done. I will investigate for the next release.

**Comment by LarsKemmann** [comment]
This works great now! 😊
