### ISSUE TITLE
Saving files with a '.' in the filename strips off the end of the file

### ISSUE THREAD

**Issue by LarsKemmann** [countincognito/Zametek.ProjectPlan#63]
Save as `example v0.1.zpp`; the result is a file called `example v0.zpp`

**Comment by countincognito** [comment]
I cannot recreate this. Can you please give me some more details please (app version, Windows/Linux/Mac, etc.)?

**Comment by LarsKemmann** [comment]
This works now on Windows 10, v0.9.0-beta.1; at least, I can't reproduce the bug anymore. 👏🏻

**Comment by LarsKemmann** [comment]
Actually, I was just able to reproduce it again: open a file named `TEST v0.1.2.3.zpp`, press Ctrl+S/select File->Save (instead of File->Save as...), and the file will be saved as `TEST v0.1.2.zpp`; for added fun, each time you press Ctrl+S you'll lose another `.`-suffix from the version number in that example filename.

**Comment by countincognito** [comment]
Thanks for this. I found the issue. It will be fixed in the next release.
