### ISSUE TITLE
Opening a file immediately marks it as having unsaved changes

### ISSUE THREAD

**Issue by LarsKemmann** [countincognito/Zametek.ProjectPlan#64]
This also triggers the "Project has unsaved changes" dialog on close.

Opening a file should not result in any unsaved changes until I actually make some kind of change to the file.

**Comment by countincognito** [comment]
This will always happen if auto-compile is on. The compilation output is part of the project file, so a recompile automatically updates the project file. If you disable auto-compilation, then it will remain unchanged.

**Comment by LarsKemmann** [comment]
I guess what I'm saying is that if the project compilation output is unchanged from the previous compilation, that should not result in the 'unsaved changes' triggering. I can appreciate that a check like that could require a bit of CPU time, but it would only ever need to happen once, when the file is first opened (or maybe if it's ever possible to implement undo/redo support, down the road).

**Comment by LarsKemmann** [comment]
@countincognito Let me know if you'd consider reopening this based on my comment above.

**Comment by countincognito** [comment]
I think I found a way to make this work. It should be completed in the next release.

**Comment by LarsKemmann** [comment]
This is fantastic!!! 🥳❤️
