### ISSUE TITLE
Charts need a dark mode style

### ISSUE THREAD

**Issue by LarsKemmann** [countincognito/Zametek.ProjectPlan#66]
- [ ] Gantt Chart
- [ ] Arrow Graph
- [ ] Resource Chart
- [ ] Earned-Value Chart

**Comment by countincognito** [comment]
I have a way to do this in the Gantt, Resource and EV charts. It will be harder to do with the Arrow Graph, since the lines for critical activities are completely black (usually). What do you think of a mid-grey background in that case?

**Comment by LarsKemmann** [comment]
That could work! Another option is to give the lines for critical activities a light-grey outline in dark mode. I'm not sure which would look better (or how much work the outline approach would require).

**Comment by countincognito** [comment]
![test6_v0_4_0-ev](https://github.com/user-attachments/assets/57757cea-f481-44bf-8d61-05df568f2019)
![test6_v0_4_0-resource](https://github.com/user-attachments/assets/4db680ed-a16a-48ff-be89-bf184aca9457)
![test6_v0_4_0-gantt](https://github.com/user-attachments/assets/7fe0cb92-127d-451b-af83-f4346dd4cc4e)
![test6_v0_4_0-arrow](https://github.com/user-attachments/assets/a6294137-aa22-4208-87da-f47a75edac6a)

**Comment by LarsKemmann** [comment]
🤌🏻 `*chef's kiss*` Fantastic!!

**Comment by LarsKemmann** [comment]
This seems to have not made it into v0.9.0-rc1?
![image](https://github.com/user-attachments/assets/5e6b29f9-d9be-4fc2-949d-14cf5199678f)

**Comment by countincognito** [comment]
I can't seem to recreate this issue with 0.9.0-rc.1. Do you have a test file I can use?

**Comment by LarsKemmann** [comment]
> I can't seem to recreate this issue with 0.9.0-rc.1. Do you have a test file I can use and some recreation steps?

Huh, you're right, it works fine! I'm so sorry, I must have mistakenly tested this one with the previous version without realizing it.

The dark mode charts look fantastic. 🤩 Yet another trick that Microsoft Project can't pull off...
