### ISSUE TITLE
Launching new app instances (with & without files) is slow

### ISSUE THREAD

**Issue by LarsKemmann** [countincognito/Zametek.ProjectPlan#67]
Performance of launching the app (time to showing any UI, in particular) is quite slow. I know you recompile the project on open, but this is even the case for a new empty project. On my (admittedly older) Win10 PC, it takes between 5-6 seconds from open a new app instance to seeing any UI.

Part of this is perceived performance (showing UI immediately, even if it's a splash screen). Part of this is actual performance (time to interactivity).

**Comment by countincognito** [comment]
I like the idea of a splash screen. I will see what I can do.

**Comment by LarsKemmann** [comment]
Feels much snappier 😊
