### ISSUE TITLE
Dark theme styling (custom UI) for the main window title bar

### ISSUE THREAD

**Issue by LarsKemmann** [countincognito/Zametek.ProjectPlan#68]
I don't know if there are any constraints on this with the panel UI system that you're using. It doesn't seem like there should be, since that system doesn't force system-decoration title bars for its floating panels.

Some references that might help:

- https://stackoverflow.com/questions/65333019/easier-way-in-net-avalonia-to-change-the-background-color-of-the-windows-syste
- https://github.com/AvaloniaUI/Avalonia/discussions/12090

**Comment by countincognito** [comment]
I think I might leave this one. It works fine in Windows 11.

**Comment by LarsKemmann** [comment]
Agreed, works well in Win11.
