### ISSUE TITLE
Opening a file by clicking on it no longer works

### ISSUE THREAD

**Issue by LarsKemmann** [countincognito/Zametek.ProjectPlan#71]
In v0.9.0-beta1 (and prior), I was able to tell Windows (10/11) to use ProjectPlan as the default app for opening `.zpp` files in File Explorer, and that actually worked: double-clicking on a file would open ProjectPlan and automatically open that file. A huge convenience!

In v0.9.0-rc1, that no longer works. I can of course still double-click a file after manually making the file type association, but ProjectPlan.NET will simply open a blank project plan. I have to go to the File menu to open the file. This is happening both with files saved from v0.9.0-beta1 and from v0.9.0-rc1.

**Comment by countincognito** [comment]
This was never actually built into the binary - file associations need to be configured by an installer. I suspect you had the old exe setup as the default application for the file type. Then when the name of the exe was changed it no longer worked. The easiest way to correct this (until an installer is available) is to change the default application for the .zpp file extension.

**Comment by countincognito** [comment]
Actually, I see what you mean. The ability to pass a file name to the desktop application has stopped working completely. It seems to have come from the changes that were introduced for the splash screen.

**Comment by LarsKemmann** [comment]
It looks like this is fixed now in 0.9.0-rc.2! 😊
