### ISSUE TITLE
Windows Installer (.msi/.msix)

### ISSUE THREAD

**Issue by LarsKemmann** [countincognito/Zametek.ProjectPlan#72]
Adding a Windows Installer would be a helpful feature for less technical users -- and could help with getting into the Microsoft Store, as well. A couple of desirable features provided by an installer:

- [ ] Place the binaries in Program Files (or, and this is probably better, install per-user instead via %AppData%).
- [ ] Register ProjectPlan.NET as the default app for opening the `.zpp` file extension.
- [ ] Add a ProjectPlan.NET shortcut to the Start menu and/or desktop.
- [ ] Make updating existing installations easier (just run the new installer).

There's a phenomenal open-source project called [WiX](https://wixtoolset.org/) for creating custom installers, along with a free Visual Studio extension called [HeatWave (Community Edition)](https://www.firegiant.com/docs/heatwave/) that automates several steps.

**Comment by countincognito** [comment]
This is definitely on the roadmap. The only issue will be that the MSI will be unsigned, since it costs a fortune to purchase a code-signing certificate. However, I believe that MSIX Bundles get automatically signed by Microsoft in their store.

**Comment by LarsKemmann** [comment]
> This is definitely on the roadmap. The only issue will be that the MSI will be unsigned, since it costs a fortune to purchase a code-signing certificate. However, I believe that MSIX Bundles get automatically signed by Microsoft in their store.

It looks like you're right: https://learn.microsoft.com/en-us/windows/msix/package/packaging-uwp-apps#generate-an-app-package-upload-file-for-store-submission

**Comment by countincognito** [comment]
Now available in [v0.9.0](https://github.com/countincognito/Zametek.ProjectPlan/releases/tag/v0.9.0)
