### ISSUE TITLE
Persist chart settings (with the project file)

### ISSUE THREAD

**Issue by LarsKemmann** [countincognito/Zametek.ProjectPlan#73]
Whether I want to see projections (Earned-Value Chart), group/annotate/label/etc. (Gantt Chart), or gray out various resources (Resource Chart) should persist; I find myself making the same changes to those controls every time I open a file. It's so automatic for me by now that I only noticed myself doing it because the new dark mode charts pulled me out of my routine!

While these settings could persist with the user profile, they are as likely to change between files for the same user as they are between users, so I would recommend persisting them as part of the project file, and not as part of the user profile.

**Comment by countincognito** [comment]
Great suggestion. I have just checked this in for the next release.

**Comment by LarsKemmann** [comment]
Thank you, I can confirm this is fixed in 0.9.0-rc.2! 🎉
